name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - aws-cost-bill-alarm
    types: [labeled]

jobs:
  terraform:
    name: 'Terraform' 
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terratest Basic'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.2'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test/cloudwatch-billing-alert-to-new-sns-consolidated-acct'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terratest Secure'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.2'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test/cloudwatch-billing-alert-to-new-sns-with-acct-id'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: 'Terratest Secure'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.2'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test/cloudwatch-billing-alert-to-pre-existing-sns-consolidated-acct'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: 'Terratest Secure'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.2'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test/cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()