name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  cloudwatch-billing-alert-to-new-sns-consolidated-acct-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_example/cloudwatch-billing-alert-to-new-sns-consolidated-acct/'

  cloudwatch-billing-alert-to-new-sns-with-acct-id-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_example/cloudwatch-billing-alert-to-new-sns-with-acct-id/'

  cloudwatch-billing-alert-to-pre-existing-sns-consolidated-acct-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_example/cloudwatch-billing-alert-to-pre-existing-sns-consolidated-acct/'

  cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_example/cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id/'
