name: tf-checks
permissions:
  id-token: write
  contents: read
on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  cloudwatch-billing-alert-to-new-sns-consolidated-acct-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/cloudwatch-billing-alert-to-new-sns-consolidated-acct/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  cloudwatch-billing-alert-to-new-sns-with-acct-id-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/cloudwatch-billing-alert-to-new-sns-with-acct-id/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  cloudwatch-billing-alert-to-pre-existing-sns-consolidated-acct-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/cloudwatch-billing-alert-to-pre-existing-sns-consolidated-acct/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/cloudwatch-billing-alert-to-pre-existing-sns-with-acct-id/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
